"use client";

import { useEffect, useState, useMemo } from 'react';
import { Store } from '@/lib/store';
import { User, Project, Assignment } from '@/lib/types';
import { calculateEmployeeFinancialValues } from '@/app/dashboard/employee-value/employeeValueEngine';
import { EmployeeValueChart } from './EmployeeValueChart';
import { EmployeeValueTable } from './EmployeeValueTable';
import { EmployeeLeaderboard } from './EmployeeLeaderboard';
import { Users, TrendingUp } from 'lucide-react';

export default function EmployeeValueDashboard() {
  const [data, setData] = useState<{ employees: User[], projects: Project[], assignments: Assignment[] }>({ employees: [], projects: [], assignments: [] });
  const [tenantId, setTenantId] = useState<string | null>(null);

  useEffect(() => {
    const auth = Store.getAuth();
    if (auth) {
      setTenantId(auth.tenantId);
      setData({
        employees: Store.getUsers(),
        projects: Store.getProjects(),
        assignments: Store.getAssignments()
      });
    }
  }, []);

  const financialData = useMemo(() => {
    if (!tenantId) return [];
    return calculateEmployeeFinancialValues(data.employees, data.projects, data.assignments, tenantId);
  }, [data, tenantId]);

  if (!tenantId) return null;

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-2 duration-500 pb-10">
      <div>
        <h1 className="text-3xl font-bold font-headline flex items-center gap-3">
          <TrendingUp className="w-8 h-8 text-primary" /> Employee Value Engine
        </h1>
        <p className="text-muted-foreground mt-1">Calculate and analyze the monetary value generated by each employee across projects.</p>
      </div>

      <EmployeeValueChart data={financialData} />
      
      <div>
         <h2 className="text-xl font-bold font-headline flex items-center gap-2 mb-4"><Users className="w-5 h-5 text-muted-foreground" /> Raw Value Data</h2>
         <EmployeeValueTable data={financialData} />
      </div>
      <EmployeeLeaderboard data={financialData} />
    </div>
  );
}